---
title: "sports betting"
format: html
editor: visual
---

```{r}
library(tidyverse)
#clear workspace
rm(list=ls())
#import data
df = read.csv("Soccer 2024.csv")
df <- df %>% select(Date,HomeTeam,AwayTeam,FTR,MaxH,MaxD,MaxA)
head(df)
```

```{r}
# compute implied probability
df$ImplProb = 1/df$MaxH + 1/df$MaxD + 1/df$MaxA
df$Margin <- 1 - df$ImplProb
df$ShouldBet <- ifelse(df$Margin > 0, 1, 0)
head(df %>% select(-MaxH,-MaxD,-MaxA))
```

```{r}
#visualize implied probabilities
plot(df$ImplProb ~ c(1:nrow(df)), 
     ylab = "Implied probability", 
     xlab = "Season games")
abline(h = 1, col = "red") # break even line
```

```{r}
#how many profitable bets?
sum(df$ShouldBet)
```

```{r}
# place bets (ignoring minor rounding errors)
bet <- 10
df$BetH <- round(ifelse(df$ShouldBet == 1, bet * 1/df$MaxH * (1+df$Margin), 0), 2)
df$BetD <- round(ifelse(df$ShouldBet == 1, bet * 1/df$MaxD * (1+df$Margin), 0), 2)
df$BetA <- round(ifelse(df$ShouldBet == 1, bet * 1/df$MaxA * (1+df$Margin), 0), 2)
head(df %>% select(-MaxH,-MaxD,-MaxA,-Margin,-ShouldBet))
```

```{r}
#calculate earnings
df$WinH <- round(ifelse(df$FTR == "H",1,0) * df$BetH * df$MaxH,2)
df$WinD <- round(ifelse(df$FTR == "D",1,0) * df$BetD * df$MaxD,2)
df$WinA <- round(ifelse(df$FTR == "A",1,0) * df$BetA * df$MaxA,2)
df$WinSum <- df$WinH + df$WinD + df$WinA
head(df %>% select(-MaxH,-MaxD,-MaxA,-Margin,-ShouldBet))

#total earnings
sum(df$WinSum)

```

```{r}
#clear workspace
rm(list=ls())

#import data
df = read.csv("Soccer 2024.csv")
df <- df %>% select(Date,HomeTeam,AwayTeam,FTR,MaxH,MaxD,MaxA)
head(df)

# compute implied probability
df$ImplProb = 1/df$MaxH + 1/df$MaxD + 1/df$MaxA
df$Margin <- 1 - df$ImplProb
df$ShouldBet <- ifelse(df$Margin > 0, 1, 0)
head(df %>% select(-MaxH,-MaxD,-MaxA)) 

#how many profitable bets?
sum(df$ShouldBet)

# place bets (ignoring minor rounding errors)
bet <- 10
df$BetH <- round(ifelse(df$ShouldBet == 1, bet * 1/df$MaxH * (1+df$Margin), 0), 2)
#plot money over time
plot(money[-1] ~ unique(df$date), 
     ylab = "Money", 
     xlab = "Season games")
```
